[tool.black]
line-length = 90
target-version = ['py38', 'py39', 'py310']
exclude = "__init__.py|.git|__pycache__|.venv|example.py"
skip-string-normalization = false

[tool.coverage.run]
omit = ["main.py"]
